### PR TITLE
Add 409 return status code to Config API resources (#465)

### PR DESCRIPTION
**Pull request by baniol**
## What did you implement:

Modified response status codes from 400 to 409 for POST requests for event types, functions, subscriptions and CORS configs resources. Updated unit tests and API docs accordingly.

## Todos:

I'm not sure if a test for `createSubscription` in `httpapi.go` should be added in scope of the task

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** NO
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by mthenw** [comment]
@baniol any idea why TravisCI is not running?

**Comment by baniol** [comment]
I have no idea why Travis is not running for this branch.

**Comment by mthenw** [comment]
@baniol can you login to travisci.org and check if there is no need to accept some ToS or something?

**Comment by baniol** [comment]
I don't see anything like that in my account, unfortunately.
I checked https://travis-ci.org/serverless/event-gateway/requests, and I can see my PR failing with "Build type disabled via repository settings (pull_request)". Could this be related?

**Comment by mthenw** [comment]
@baniol oh, I see. I fixed that.

**Comment by mthenw** [comment]
@baniol looks great. I will merge it in upcoming days.

**Pull request merged**
